spring:
  application:
    name: unionPay-config-server
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 9092
          zkNodes: zookeeper
          defaultZkPort: 2181
          autoCreateTopics: true
          autoAddPartitions: true
    config:
      server:
        git:
          uri: file:///home/lirenhao/unionPay/unionpay-config-repo
          username: lirenhao
          password: liRenhao0912