version: '3'

networks:
  default:
    external:
      name: unionPay

volumes:
  kafka:
  mongo:
  mysql:

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=merInfo:1:1:compact,orgInfo:1:1:compact,alipay:1:1:compact,aliMerStaying:1:1:compact,wechat:1:1:compact,wxMerStaying:1:1:compact
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka:/kafka

  mongo:
    image: mongo
    volumes:
      - mongo:/data
  
  manager:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    ports:
      - "9000:8081"

  restheart:
    image: softinstigate/restheart
    depends_on:
      - mongo
    volumes:
      - ./restheart/etc:/opt/restheart/etc:ro

  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=unionPay
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql

  configserver:
    image: lirenhao/configserver:1.0.0
    environment:
      - SPRING_CONFIG_LOCATION=/usr/src/config/application.properties
    volumes:
      - ./config:/usr/src/config
    ports:
      - "9005:8080"