version: '3'

networks:
  default:
    external:
      name: unionPay

services:

  aggservice:
    image: cuitaocrazy/agg-service:1.0.2
    environment:
      - HOST=zookeeper:2181
    volumes:
      - ./agg/agg_scripts:/opt/aggservice/agg_scripts
      - ./agg/reset_offset_agg_scripts:/opt/aggservice/reset_offset_agg_scripts
      - ./agg/graphql_scripts:/opt/aggservice/graphql_scripts

  plantask:
    image: lirenhao/plantask:1.0.1
    environment:
      - SPRING_PROFILES_ACTIVE=pro

  alipay:
    image: lirenhao/alipay:1.0.1
    environment:
      - SPRING_PROFILES_ACTIVE=pro
    ports:
      - "9003:8080" 

  wechat:
    image: 1121807592/wxpay:1.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=pro
    ports:
      - "9002:8080" 

  alimerstay:
    image: anatman/alipaymchenter:1.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=pro

  wxmerstay:
    image: anatman/wechatmchenter:1.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=pro 

  userscan:
    image: 200342/userscan:1.0.2
    environment:
      - SPRING_PROFILES_ACTIVE=pro
    ports:
      - "9001:8080" 

  bankmanager:
    image: tianyuan/bankservicepc:1.0.3
    environment:
      - SPRING_PROFILES_ACTIVE=pro
    ports:
      - "9004:8080"